---
- hosts: anthonyhanna.com
  become: yes
  tasks: 
  - name: update the machines
    apt:
      name: "*"
      update_cache: yes
      state: latest

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
 
...

